FORMAT: 1A
HOST: http://docs.sba.apiary.io/

# SBA-Front API
SBA-Front API 

# Group Account Summary
Services involved in **Account Summary API**

## Account Summary [/hbs/accountsummary/load]
### base load [GET]
+ Response 200 (application/json)

        {
          "widgets" : [ {
            "status" : "OPEN",
            "totalPostedBalance" : "$40000.0",
            "totalAvailableBalance" : "$36000.0",
            "checkingSavingMoneyMarketAccounts" : [ {
              "nick" : "Checking 1",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "0000",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 2",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : false,
              "number" : "1111",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 3",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "2222",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 4",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : false,
              "number" : "3333",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            } ],
            "literals" : {
              "title" : "Checking, Savings and Money Market Accounts",
              "header" : {
                "alert" : "Alert",
                "account" : "Account",
                "type" : "Type",
                "postedBalance" : "Posted Balance",
                "availableBalance" : "Available Balance"
              },
              "footer" : {
                "total" : "Total"
              }
            }
          }, {
            "status" : "CLOSE",
            "totalBalance" : "$10000.0",
            "certificateDepositRetirementAccounts" : [ {
              "nick" : "Retirement 0",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "0000",
              "type" : "CD",
              "amount" : 0
            }, {
              "nick" : "Retirement 1",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "1111",
              "type" : "CD",
              "amount" : 1000
            }, {
              "nick" : "Retirement 2",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "2222",
              "type" : "CD",
              "amount" : 2000
            }, {
              "nick" : "Retirement 3",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "3333",
              "type" : "CD",
              "amount" : 3000
            }, {
              "nick" : "Retirement 4",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "4444",
              "type" : "CD",
              "amount" : 4000
            } ],
            "literals" : {
              "title" : "Certificate of Deposit and Retirement Accounts",
              "header" : {
                "alert" : "Alert",
                "account" : "Account",
                "type" : "Type",
                "amount" : "Current Balance"
              },
              "footer" : {
                "total" : "Total"
              }
            }
          }, {
            "status" : "OPEN",
            "totalBalance" : "$1200.0",
            "creditCardLineCreditOverdraftProtectionAccounts" : [ {
              "nick" : "Credit 0",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 0
              }, {
                "key" : "Available credit",
                "value" : 0
              }, {
                "key" : "Next Payment Date",
                "value" : 1383917616224
              }, {
                "key" : "Min. Payment Amount",
                "value" : 200
              } ],
              "alert" : true,
              "number" : "0000",
              "type" : "CREDIT_CARD"
            }, {
              "nick" : "Credit 1",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 200
              }, {
                "key" : "Available credit",
                "value" : 1000
              } ],
              "alert" : false,
              "number" : "1111",
              "type" : "CREDIT_LINE"
            }, {
              "nick" : "Credit 2",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 400
              }, {
                "key" : "Available credit",
                "value" : 2000
              }, {
                "key" : "Next Payment Date",
                "value" : 1383917616224
              }, {
                "key" : "Min. Payment Amount",
                "value" : 200
              } ],
              "alert" : true,
              "number" : "2222",
              "type" : "CREDIT_CARD"
            }, {
              "nick" : "Credit 3",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 600
              }, {
                "key" : "Available credit",
                "value" : 3000
              } ],
              "alert" : false,
              "number" : "3333",
              "type" : "CREDIT_LINE"
            } ],
            "literals" : {
              "title" : "Credit Card, Line of Credit and Overdraft Protection",
              "header" : {
                "alert" : "Alert",
                "account" : "Account",
                "type" : "Type",
                "details" : "Details"
              },
              "footer" : {
                "total" : "Total"
              }
            }
          }, {
            "status" : "CLOSE",
            "totalBalance" : "$6000.0",
            "loanMortgateAccounts" : [ {
              "nick" : "Loan 0",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 0
              }, {
                "key" : "Next Payment Date",
                "value" : 1383917616226
              }, {
                "key" : "Min. Payment Amount",
                "value" : 0
              } ],
              "alert" : true,
              "number" : "0000",
              "type" : "LOAN_ALS"
            }, {
              "nick" : "Loan 1",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 1000
              }, {
                "key" : "Next Payment Date",
                "value" : 1383917616226
              }, {
                "key" : "Min. Payment Amount",
                "value" : 200
              } ],
              "alert" : false,
              "number" : "1111",
              "type" : "LOAN_ALS"
            }, {
              "nick" : "Loan 2",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 2000
              }, {
                "key" : "Next Payment Date",
                "value" : 1383917616226
              }, {
                "key" : "Min. Payment Amount",
                "value" : 400
              } ],
              "alert" : true,
              "number" : "2222",
              "type" : "LOAN_LOC"
            }, {
              "nick" : "Loan 3",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 3000
              }, {
                "key" : "Next Payment Date",
                "value" : 1383917616226
              }, {
                "key" : "Min. Payment Amount",
                "value" : 600
              } ],
              "alert" : false,
              "number" : "3333",
              "type" : "LOAN_LOC"
            } ],
            "literals" : {
              "title" : "Loan and Mortgage Accounts",
              "header" : {
                "alert" : "Alert",
                "account" : "Account",
                "type" : "Type",
                "details" : "Details"
              },
              "footer" : {
                "total" : "Total",
                "legal" : "* Balance shown in an estimated one-day payoff balance."
              }
            }
          }, {
            "status" : "OPEN",
            "total" : "$6000.0",
            "investmentAccounts" : [ {
              "nick" : "Credit 0",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "0000",
              "type" : "INV",
              "amount" : 0
            }, {
              "nick" : "Credit 1",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : false,
              "number" : "1111",
              "type" : "INV",
              "amount" : 1000
            }, {
              "nick" : "Credit 2",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "2222",
              "type" : "INV",
              "amount" : 2000
            }, {
              "nick" : "Credit 3",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : false,
              "number" : "3333",
              "type" : "INV",
              "amount" : 3000
            } ],
            "literals" : {
              "title" : "Investment Accounts",
              "header" : {
                "alert" : "Alert",
                "account" : "Account",
                "type" : "Type",
                "amount" : "Value"
              },
              "footer" : {
                "total" : "Total"
              }
            }
          }, {
            "status" : "OPEN",
            "total" : "$15000.0",
            "realStateAccounts" : [ {
              "nick" : "Real 0",
              "percent" : "0.00%",
              "amount" : 0
            }, {
              "nick" : "Real 1",
              "percent" : "10.00%",
              "amount" : 1500
            }, {
              "nick" : "Real 2",
              "percent" : "20.00%",
              "amount" : 3000
            }, {
              "nick" : "Real 3",
              "percent" : "30.00%",
              "amount" : 4500
            }, {
              "nick" : "Real 4",
              "percent" : "40.00%",
              "amount" : 6000
            } ],
            "literals" : {
              "title" : "Real State",
              "header" : {
                "description" : "Description",
                "percent" : "% Home Equity Amount",
                "amount" : "Home Equity Amount"
              },
              "footer" : {
                "total" : "Total"
              }
            }
          }, {
            "status" : "OPEN",
            "rewardsAccounts" : [ {
              "nick" : "Rewards 0",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "balance" : 0,
              "alert" : true,
              "number" : "0000",
              "type" : "REWARDS"
            }, {
              "nick" : "Rewards 1",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "balance" : 1000,
              "alert" : false,
              "number" : "1111",
              "type" : "REWARDS"
            }, {
              "nick" : "Rewards 2",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "balance" : 2000,
              "alert" : true,
              "number" : "2222",
              "type" : "REWARDS"
            }, {
              "nick" : "Rewards 3",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "balance" : 3000,
              "alert" : false,
              "number" : "3333",
              "type" : "REWARDS"
            } ],
            "literals" : {
              "title" : "Rewards",
              "header" : {
                "alert" : "Alert",
                "account" : "Account",
                "number" : "Number",
                "amount" : "Balance"
              }
            }
          } ]
        }
        
## Yoodle [/hbs/accountsummary/yodlee]
### yoodle [GET]
+ Response 200 (application/json)
      
        {
          "widgets" : [ {
            "status" : "OPEN",
            "totalPostedBalance" : "$140000.0",
            "totalAvailableBalance" : "$126000.0",
            "checkingSavingMoneyMarketAccounts" : [ {
              "nick" : "Checking 1",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "0000",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 2",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : false,
              "number" : "1111",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 3",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "2222",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 4",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : false,
              "number" : "3333",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 5",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "4444",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 6",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : false,
              "number" : "5555",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 7",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "6666",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 8",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : false,
              "number" : "7777",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 9",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "8888",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 10",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : false,
              "number" : "9999",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 11",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "10101010",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 12",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : false,
              "number" : "11111111",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 13",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "12121212",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 14",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : false,
              "number" : "13131313",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            } ],
            "literals" : {
              "title" : "Checking, Savings and Money Market Accounts",
              "header" : {
                "alert" : "Alert",
                "account" : "Account",
                "type" : "Type",
                "postedBalance" : "Posted Balance",
                "availableBalance" : "Available Balance"
              },
              "footer" : {
                "total" : "Total"
              }
            }
          }, {
            "status" : "CLOSE",
            "totalBalance" : "$10000.0",
            "certificateDepositRetirementAccounts" : [ {
              "nick" : "Retirement 0",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "0000",
              "type" : "CD",
              "amount" : 0
            }, {
              "nick" : "Retirement 1",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "1111",
              "type" : "CD",
              "amount" : 1000
            }, {
              "nick" : "Retirement 2",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "2222",
              "type" : "CD",
              "amount" : 2000
            }, {
              "nick" : "Retirement 3",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "3333",
              "type" : "CD",
              "amount" : 3000
            }, {
              "nick" : "Retirement 4",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "4444",
              "type" : "CD",
              "amount" : 4000
            } ],
            "literals" : {
              "title" : "Certificate of Deposit and Retirement Accounts",
              "header" : {
                "alert" : "Alert",
                "account" : "Account",
                "type" : "Type",
                "amount" : "Current Balance"
              },
              "footer" : {
                "total" : "Total"
              }
            }
          }, {
            "status" : "OPEN",
            "totalBalance" : "$11000.0",
            "creditCardLineCreditOverdraftProtectionAccounts" : [ {
              "nick" : "Credit 0",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 0
              }, {
                "key" : "Available credit",
                "value" : 0
              }, {
                "key" : "Next Payment Date",
                "value" : 1383917616758
              }, {
                "key" : "Min. Payment Amount",
                "value" : 200
              } ],
              "alert" : true,
              "number" : "0000",
              "type" : "CREDIT_CARD"
            }, {
              "nick" : "Credit 1",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 200
              }, {
                "key" : "Available credit",
                "value" : 1000
              } ],
              "alert" : false,
              "number" : "1111",
              "type" : "CREDIT_LINE"
            }, {
              "nick" : "Credit 2",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 400
              }, {
                "key" : "Available credit",
                "value" : 2000
              }, {
                "key" : "Next Payment Date",
                "value" : 1383917616758
              }, {
                "key" : "Min. Payment Amount",
                "value" : 200
              } ],
              "alert" : true,
              "number" : "2222",
              "type" : "CREDIT_CARD"
            }, {
              "nick" : "Credit 3",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 600
              }, {
                "key" : "Available credit",
                "value" : 3000
              } ],
              "alert" : false,
              "number" : "3333",
              "type" : "CREDIT_LINE"
            }, {
              "nick" : "Credit 4",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 800
              }, {
                "key" : "Available credit",
                "value" : 4000
              } ],
              "alert" : true,
              "number" : "4444",
              "type" : "CREDIT_LINE"
            }, {
              "nick" : "Credit 5",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 1000
              }, {
                "key" : "Available credit",
                "value" : 5000
              } ],
              "alert" : false,
              "number" : "5555",
              "type" : "CREDIT_LINE"
            }, {
              "nick" : "Credit 6",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 1200
              }, {
                "key" : "Available credit",
                "value" : 6000
              } ],
              "alert" : true,
              "number" : "6666",
              "type" : "CREDIT_LINE"
            }, {
              "nick" : "Credit 7",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 1400
              }, {
                "key" : "Available credit",
                "value" : 7000
              } ],
              "alert" : false,
              "number" : "7777",
              "type" : "CREDIT_LINE"
            }, {
              "nick" : "Credit 8",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 1600
              }, {
                "key" : "Available credit",
                "value" : 8000
              } ],
              "alert" : true,
              "number" : "8888",
              "type" : "CREDIT_LINE"
            }, {
              "nick" : "Credit 9",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 1800
              }, {
                "key" : "Available credit",
                "value" : 9000
              } ],
              "alert" : false,
              "number" : "9999",
              "type" : "CREDIT_LINE"
            }, {
              "nick" : "Credit 10",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 2000
              }, {
                "key" : "Available credit",
                "value" : 10000
              } ],
              "alert" : true,
              "number" : "10101010",
              "type" : "CREDIT_LINE"
            } ],
            "literals" : {
              "title" : "Credit Card, Line of Credit and Overdraft Protection",
              "header" : {
                "alert" : "Alert",
                "account" : "Account",
                "type" : "Type",
                "details" : "Details"
              },
              "footer" : {
                "total" : "Total"
              }
            }
          }, {
            "status" : "CLOSE",
            "totalBalance" : "$15000.0",
            "loanMortgateAccounts" : [ {
              "nick" : "Loan 0",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 0
              }, {
                "key" : "Next Payment Date",
                "value" : 1383917616758
              }, {
                "key" : "Min. Payment Amount",
                "value" : 0
              } ],
              "alert" : true,
              "number" : "0000",
              "type" : "LOAN_ALS"
            }, {
              "nick" : "Loan 1",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 1000
              }, {
                "key" : "Next Payment Date",
                "value" : 1383917616758
              }, {
                "key" : "Min. Payment Amount",
                "value" : 200
              } ],
              "alert" : false,
              "number" : "1111",
              "type" : "LOAN_ALS"
            }, {
              "nick" : "Loan 2",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 2000
              }, {
                "key" : "Next Payment Date",
                "value" : 1383917616758
              }, {
                "key" : "Min. Payment Amount",
                "value" : 400
              } ],
              "alert" : true,
              "number" : "2222",
              "type" : "LOAN_LOC"
            }, {
              "nick" : "Loan 3",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 3000
              }, {
                "key" : "Next Payment Date",
                "value" : 1383917616758
              }, {
                "key" : "Min. Payment Amount",
                "value" : 600
              } ],
              "alert" : false,
              "number" : "3333",
              "type" : "LOAN_LOC"
            }, {
              "nick" : "Loan 4",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 4000
              }, {
                "key" : "Next Payment Date",
                "value" : 1383917616759
              }, {
                "key" : "Min. Payment Amount",
                "value" : 800
              } ],
              "alert" : true,
              "number" : "4444",
              "type" : "LOAN_ALS"
            }, {
              "nick" : "Loan 5",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 5000
              }, {
                "key" : "Next Payment Date",
                "value" : 1383917616759
              }, {
                "key" : "Min. Payment Amount",
                "value" : 1000
              } ],
              "alert" : false,
              "number" : "5555",
              "type" : "LOAN_ALS"
            } ],
            "literals" : {
              "title" : "Loan and Mortgage Accounts",
              "header" : {
                "alert" : "Alert",
                "account" : "Account",
                "type" : "Type",
                "details" : "Details"
              },
              "footer" : {
                "total" : "Total",
                "legal" : "* Balance shown in an estimated one-day payoff balance."
              }
            }
          }, {
            "status" : "OPEN",
            "total" : "$6000.0",
            "investmentAccounts" : [ {
              "nick" : "Credit 0",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "0000",
              "type" : "INV",
              "amount" : 0
            }, {
              "nick" : "Credit 1",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : false,
              "number" : "1111",
              "type" : "INV",
              "amount" : 1000
            }, {
              "nick" : "Credit 2",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "2222",
              "type" : "INV",
              "amount" : 2000
            }, {
              "nick" : "Credit 3",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : false,
              "number" : "3333",
              "type" : "INV",
              "amount" : 3000
            } ],
            "literals" : {
              "title" : "Investment Accounts",
              "header" : {
                "alert" : "Alert",
                "account" : "Account",
                "type" : "Type",
                "amount" : "Value"
              },
              "footer" : {
                "total" : "Total"
              }
            }
          }, {
            "status" : "OPEN",
            "total" : "$15000.0",
            "realStateAccounts" : [ {
              "nick" : "Real 0",
              "percent" : "0.00%",
              "amount" : 0
            }, {
              "nick" : "Real 1",
              "percent" : "10.00%",
              "amount" : 1500
            }, {
              "nick" : "Real 2",
              "percent" : "20.00%",
              "amount" : 3000
            }, {
              "nick" : "Real 3",
              "percent" : "30.00%",
              "amount" : 4500
            }, {
              "nick" : "Real 4",
              "percent" : "40.00%",
              "amount" : 6000
            } ],
            "literals" : {
              "title" : "Real State",
              "header" : {
                "description" : "Description",
                "percent" : "% Home Equity Amount",
                "amount" : "Home Equity Amount"
              },
              "footer" : {
                "total" : "Total"
              }
            }
          }, {
            "status" : "OPEN",
            "rewardsAccounts" : [ {
              "nick" : "Rewards 0",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "balance" : 0,
              "alert" : true,
              "number" : "0000",
              "type" : "REWARDS"
            }, {
              "nick" : "Rewards 1",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "balance" : 1000,
              "alert" : false,
              "number" : "1111",
              "type" : "REWARDS"
            }, {
              "nick" : "Rewards 2",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "balance" : 2000,
              "alert" : true,
              "number" : "2222",
              "type" : "REWARDS"
            }, {
              "nick" : "Rewards 3",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "balance" : 3000,
              "alert" : false,
              "number" : "3333",
              "type" : "REWARDS"
            } ],
            "literals" : {
              "title" : "Rewards",
              "header" : {
                "alert" : "Alert",
                "account" : "Account",
                "number" : "Number",
                "amount" : "Balance"
              }
            }
          } ]
        }
       

## Credit Card [/hbs/accountsummary/credit-card]
### credit card [GET]
El content-type json, se utilizará únicamente en modo de desarrollo, ya que para utilizar las llamadas AJAX será necesario solicitar el contenido como text/html

+ Request 

    + Headers

            Accept: text/html, application/json

+ Response 200 (application/json)

        {
          "widgets" : [ {
            "status" : "OPEN",
            "totalPostedBalance" : "$40000.0",
            "totalAvailableBalance" : "$36000.0",
            "checkingSavingMoneyMarketAccounts" : [ {
              "nick" : "Checking 1",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "0000",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 2",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : false,
              "number" : "1111",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 3",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "2222",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 4",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : false,
              "number" : "3333",
              "type" : "CHECKING",
              "posted" : 10000,
              "available" : 9000
            } ],
            "literals" : {
              "title" : "Checking, Savings and Money Market Accounts",
              "header" : {
                "alert" : "Alert",
                "account" : "Account",
                "type" : "Type",
                "postedBalance" : "Posted Balance",
                "availableBalance" : "Available Balance"
              },
              "footer" : {
                "total" : "Total"
              }
            }
          }, {
            "status" : "CLOSE",
            "totalBalance" : "$10000.0",
            "certificateDepositRetirementAccounts" : [ {
              "nick" : "Retirement 0",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "0000",
              "type" : "CD",
              "amount" : 0
            }, {
              "nick" : "Retirement 1",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "1111",
              "type" : "CD",
              "amount" : 1000
            }, {
              "nick" : "Retirement 2",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "2222",
              "type" : "CD",
              "amount" : 2000
            }, {
              "nick" : "Retirement 3",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "3333",
              "type" : "CD",
              "amount" : 3000
            }, {
              "nick" : "Retirement 4",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "4444",
              "type" : "CD",
              "amount" : 4000
            } ],
            "literals" : {
              "title" : "Certificate of Deposit and Retirement Accounts",
              "header" : {
                "alert" : "Alert",
                "account" : "Account",
                "type" : "Type",
                "amount" : "Current Balance"
              },
              "footer" : {
                "total" : "Total"
              }
            }
          }, {
            "status" : "OPEN",
            "totalBalance" : "$3000.0",
            "creditCardLineCreditOverdraftProtectionAccounts" : [ {
              "nick" : "Credit 0",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 0
              }, {
                "key" : "Available credit",
                "value" : 0
              }, {
                "key" : "Next Payment Date",
                "value" : 1383917616847
              }, {
                "key" : "Min. Payment Amount",
                "value" : 200
              } ],
              "alert" : true,
              "number" : "0000",
              "type" : "CREDIT_CARD"
            }, {
              "nick" : "Credit 1",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 200
              }, {
                "key" : "Available credit",
                "value" : 1000
              } ],
              "alert" : false,
              "number" : "1111",
              "type" : "CREDIT_LINE"
            }, {
              "nick" : "Credit 2",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 400
              }, {
                "key" : "Available credit",
                "value" : 2000
              }, {
                "key" : "Next Payment Date",
                "value" : 1383917616847
              }, {
                "key" : "Min. Payment Amount",
                "value" : 200
              } ],
              "alert" : true,
              "number" : "2222",
              "type" : "CREDIT_CARD"
            }, {
              "nick" : "Credit 3",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 600
              }, {
                "key" : "Available credit",
                "value" : 3000
              } ],
              "alert" : false,
              "number" : "3333",
              "type" : "CREDIT_LINE"
            }, {
              "nick" : "Credit 4",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 800
              }, {
                "key" : "Available credit",
                "value" : 4000
              } ],
              "alert" : true,
              "number" : "4444",
              "type" : "CREDIT_LINE"
            }, {
              "nick" : "Credit 5",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 1000
              }, {
                "key" : "Available credit",
                "value" : 5000
              } ],
              "alert" : false,
              "number" : "5555",
              "type" : "CREDIT_LINE"
            } ],
            "literals" : {
              "title" : "Credit Card, Line of Credit and Overdraft Protection",
              "header" : {
                "alert" : "Alert",
                "account" : "Account",
                "type" : "Type",
                "details" : "Details"
              },
              "footer" : {
                "total" : "Total"
              }
            }
          }, {
            "status" : "CLOSE",
            "totalBalance" : "$6000.0",
            "loanMortgateAccounts" : [ {
              "nick" : "Loan 0",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 0
              }, {
                "key" : "Next Payment Date",
                "value" : 1383917616847
              }, {
                "key" : "Min. Payment Amount",
                "value" : 0
              } ],
              "alert" : true,
              "number" : "0000",
              "type" : "LOAN_ALS"
            }, {
              "nick" : "Loan 1",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 1000
              }, {
                "key" : "Next Payment Date",
                "value" : 1383917616847
              }, {
                "key" : "Min. Payment Amount",
                "value" : 200
              } ],
              "alert" : false,
              "number" : "1111",
              "type" : "LOAN_ALS"
            }, {
              "nick" : "Loan 2",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 2000
              }, {
                "key" : "Next Payment Date",
                "value" : 1383917616847
              }, {
                "key" : "Min. Payment Amount",
                "value" : 400
              } ],
              "alert" : true,
              "number" : "2222",
              "type" : "LOAN_LOC"
            }, {
              "nick" : "Loan 3",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 3000
              }, {
                "key" : "Next Payment Date",
                "value" : 1383917616847
              }, {
                "key" : "Min. Payment Amount",
                "value" : 600
              } ],
              "alert" : false,
              "number" : "3333",
              "type" : "LOAN_LOC"
            } ],
            "literals" : {
              "title" : "Loan and Mortgage Accounts",
              "header" : {
                "alert" : "Alert",
                "account" : "Account",
                "type" : "Type",
                "details" : "Details"
              },
              "footer" : {
                "total" : "Total",
                "legal" : "* Balance shown in an estimated one-day payoff balance."
              }
            }
          }, {
            "status" : "OPEN",
            "total" : "$6000.0",
            "investmentAccounts" : [ {
              "nick" : "Credit 0",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "0000",
              "type" : "INV",
              "amount" : 0
            }, {
              "nick" : "Credit 1",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : false,
              "number" : "1111",
              "type" : "INV",
              "amount" : 1000
            }, {
              "nick" : "Credit 2",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : true,
              "number" : "2222",
              "type" : "INV",
              "amount" : 2000
            }, {
              "nick" : "Credit 3",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "alert" : false,
              "number" : "3333",
              "type" : "INV",
              "amount" : 3000
            } ],
            "literals" : {
              "title" : "Investment Accounts",
              "header" : {
                "alert" : "Alert",
                "account" : "Account",
                "type" : "Type",
                "amount" : "Value"
              },
              "footer" : {
                "total" : "Total"
              }
            }
          }, {
            "status" : "OPEN",
            "total" : "$15000.0",
            "realStateAccounts" : [ {
              "nick" : "Real 0",
              "percent" : "0.00%",
              "amount" : 0
            }, {
              "nick" : "Real 1",
              "percent" : "10.00%",
              "amount" : 1500
            }, {
              "nick" : "Real 2",
              "percent" : "20.00%",
              "amount" : 3000
            }, {
              "nick" : "Real 3",
              "percent" : "30.00%",
              "amount" : 4500
            }, {
              "nick" : "Real 4",
              "percent" : "40.00%",
              "amount" : 6000
            } ],
            "literals" : {
              "title" : "Real State",
              "header" : {
                "description" : "Description",
                "percent" : "% Home Equity Amount",
                "amount" : "Home Equity Amount"
              },
              "footer" : {
                "total" : "Total"
              }
            }
          }, {
            "status" : "OPEN",
            "rewardsAccounts" : [ {
              "nick" : "Rewards 0",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "balance" : 0,
              "alert" : true,
              "number" : "0000",
              "type" : "REWARDS"
            }, {
              "nick" : "Rewards 1",
              "bbvaCompassAccount" : true,
              "lastUpdated" : "As of 00:00 hours ago",
              "balance" : 1000,
              "alert" : false,
              "number" : "1111",
              "type" : "REWARDS"
            }, {
              "nick" : "Rewards 2",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "balance" : 2000,
              "alert" : true,
              "number" : "2222",
              "type" : "REWARDS"
            }, {
              "nick" : "Rewards 3",
              "bbvaCompassAccount" : false,
              "lastUpdated" : "As of 00:00 hours ago",
              "balance" : 3000,
              "alert" : false,
              "number" : "3333",
              "type" : "REWARDS"
            } ],
            "literals" : {
              "title" : "Rewards",
              "header" : {
                "alert" : "Alert",
                "account" : "Account",
                "number" : "Number",
                "amount" : "Balance"
              }
            }
          } ]
        }
        

+ Response 200 (text/html)

        <html>
             <body>
                 to be defined
             </body>
        </html>