FORMAT: 1A
HOST: http://docs.sba.apiary.io/

# SBA-Front API
SBA-Front API 

# Group Account Summary
Services involved in **Account Summary API**

## Account Summary [/accountsummary/load]
### [GET]
+ Response 200 (application/json)

        {"summary":
        {
          "menu" : {
            "summary" : {
              "url" : "/SBA/app/accountsummary/load",
              "active" : true
            }
          },
          "profile" : {
            "name" : "John McClane",
            "messages" : 50,
            "lastSignIn" : {
              "iso8601" : "2014-01-02T10:28:57.449Z",
              "humanReadability" : "Thu, 01/02/2014 at 10:28 AM"
            }
          },
          "widgets" : [ {
            "type" : "CHECKING_SAVING",
            "isOpen" : false,
            "checkingSavingMoneyMarketAccounts" : [ {
              "nick" : "Checking 1",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:28",
              "type" : "CHECKING",
              "number" : "0000",
              "posted" : "$10,000.00",
              "available" : "$9,000.00"
            }, {
              "nick" : "Checking 2",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "10:28",
              "type" : "CHECKING",
              "number" : "1111",
              "posted" : "$10,000.00",
              "available" : "$9,000.00"
            }, {
              "nick" : "Checking 3",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:28",
              "type" : "CHECKING",
              "number" : "2222",
              "posted" : "$10,000.00",
              "available" : "$9,000.00"
            }, {
              "nick" : "Checking 4",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "10:28",
              "type" : "CHECKING",
              "number" : "3333",
              "posted" : "$10,000.00",
              "available" : "$9,000.00"
            } ],
            "totalPosted" : "$40,000.00",
            "totalAvailable" : "$36,000.00"
          }, {
            "type" : "CD_RETIREMENT",
            "isOpen" : true,
            "certificateDepositRetirementAccounts" : [ {
              "nick" : "Retirement 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:28",
              "type" : "CD",
              "number" : "0000",
              "amount" : "$00.00"
            }, {
              "nick" : "Retirement 1",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:28",
              "type" : "CD",
              "number" : "1111",
              "amount" : "$1,000.00"
            }, {
              "nick" : "Retirement 2",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:28",
              "type" : "CD",
              "number" : "2222",
              "amount" : "$2,000.00"
            }, {
              "nick" : "Retirement 3",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:28",
              "type" : "CD",
              "number" : "3333",
              "amount" : "$3,000.00"
            }, {
              "nick" : "Retirement 4",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:28",
              "type" : "CD",
              "number" : "4444",
              "amount" : "$4,000.00"
            } ],
            "total" : "$10,000.00"
          }, {
            "type" : "INVESTMENT",
            "isOpen" : false,
            "investmentAccounts" : [ {
              "nick" : "Credit 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:28",
              "type" : "INV",
              "number" : "0000",
              "amount" : "$00.00"
            }, {
              "nick" : "Credit 1",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "10:28",
              "type" : "INV",
              "number" : "1111",
              "amount" : "$1,000.00"
            }, {
              "nick" : "Credit 2",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:28",
              "type" : "INV",
              "number" : "2222",
              "amount" : "$2,000.00"
            }, {
              "nick" : "Credit 3",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "10:28",
              "type" : "INV",
              "number" : "3333",
              "amount" : "$3,000.00"
            } ],
            "total" : "$6,000.00"
          }, {
            "type" : "CREDITCARD_LINEOFCREDIT_OVERDRAFTPROTECTION",
            "isOpen" : true,
            "creditCardLineCreditOverdraftProtectionAccounts" : [ {
              "nick" : "Credit 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:28",
              "type" : "CREDIT_CARD",
              "number" : "0000",
              "posted" : "$00.00",
              "available" : 0,
              "nextDate" : "01/02/2014",
              "minAmount" : "$200.00"
            }, {
              "nick" : "Credit 1",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "10:28",
              "type" : "CREDIT_LINE",
              "number" : "1111",
              "posted" : "$200.00",
              "available" : 1000,
              "nextDate" : "01/02/2014",
              "minAmount" : "$200.00"
            }, {
              "nick" : "Credit 2",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:28",
              "type" : "CREDIT_CARD",
              "number" : "2222",
              "posted" : "$400.00",
              "available" : 2000,
              "nextDate" : "01/02/2014",
              "minAmount" : "$200.00"
            }, {
              "nick" : "Credit 3",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "10:28",
              "type" : "CREDIT_LINE",
              "number" : "3333",
              "posted" : "$600.00",
              "available" : 3000,
              "nextDate" : "01/02/2014",
              "minAmount" : "$200.00"
            } ],
            "total" : "$1,200.00"
          }, {
            "type" : "LOAN_MORTGAGE",
            "isOpen" : false,
            "loanMortgateAccounts" : [ {
              "nick" : "Loan 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:28",
              "type" : "LOAN_ALS",
              "number" : "0000",
              "payOff" : "$00.00",
              "nextDate" : "01/02/2014",
              "nextAmount" : "$00.00"
            }, {
              "nick" : "Loan 1",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "10:28",
              "type" : "LOAN_ALS",
              "number" : "1111",
              "payOff" : "$1,000.00",
              "nextDate" : "01/02/2014",
              "nextAmount" : "$200.00"
            }, {
              "nick" : "Loan 2",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:28",
              "type" : "LOAN_LOC",
              "number" : "2222",
              "payOff" : "$2,000.00",
              "nextDate" : "01/02/2014",
              "nextAmount" : "$400.00"
            }, {
              "nick" : "Loan 3",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "10:28",
              "type" : "LOAN_LOC",
              "number" : "3333",
              "payOff" : "$3,000.00",
              "nextDate" : "01/02/2014",
              "nextAmount" : "$600.00"
            } ],
            "total" : "$6,000.00"
          }, {
            "type" : "REAL_ESTATE",
            "isOpen" : false,
            "realEstateAccounts" : [ {
              "nick" : "Real 0",
              "bbvaCompassAccount" : true,
              "percent" : "00.00%",
              "amount" : "$00.00"
            }, {
              "nick" : "Real 1",
              "bbvaCompassAccount" : true,
              "percent" : "10.00%",
              "amount" : "$10.00"
            }, {
              "nick" : "Real 2",
              "bbvaCompassAccount" : true,
              "percent" : "20.00%",
              "amount" : "$20.00"
            }, {
              "nick" : "Real 3",
              "bbvaCompassAccount" : true,
              "percent" : "30.00%",
              "amount" : "$30.00"
            }, {
              "nick" : "Real 4",
              "bbvaCompassAccount" : true,
              "percent" : "40.00%",
              "amount" : "$40.00"
            } ],
            "total" : "$100.00"
          }, {
            "type" : "REWARDS",
            "isOpen" : false,
            "rewardsAccounts" : [ {
              "nick" : "Rewards 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:28",
              "type" : "REWARDS",
              "balance" : "$00.00",
              "number" : "0000"
            }, {
              "nick" : "Rewards 1",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "10:28",
              "type" : "REWARDS",
              "balance" : "$1,000.00",
              "number" : "1111"
            }, {
              "nick" : "Rewards 2",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:28",
              "type" : "REWARDS",
              "balance" : "$2,000.00",
              "number" : "2222"
            }, {
              "nick" : "Rewards 3",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "10:28",
              "type" : "REWARDS",
              "balance" : "$3,000.00",
              "number" : "3333"
            } ]
          } ]
        }}
        
## Account Summary con filtro [/accountsummary/load/{filter}]

### [GET]
+ Parameters
    + filter (required, enumeration) ... compass, external, personal, business


+ Response 200 (application/json)

        {"widgets":
        [ {
          "type" : "CHECKING_SAVING",
          "isOpen" : true,
          "checkingSavingMoneyMarketAccounts" : [ {
            "nick" : "Checking 1",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "CHECKING",
            "number" : "0000",
            "posted" : "$10,000.00",
            "available" : "$9,000.00"
          }, {
            "nick" : "Checking 2",
            "bbvaCompassAccount" : true,
            "alert" : false,
            "lastUpdated" : "10:29",
            "type" : "CHECKING",
            "number" : "1111",
            "posted" : "$10,000.00",
            "available" : "$9,000.00"
          }, {
            "nick" : "Checking 3",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "CHECKING",
            "number" : "2222",
            "posted" : "$10,000.00",
            "available" : "$9,000.00"
          }, {
            "nick" : "Checking 4",
            "bbvaCompassAccount" : true,
            "alert" : false,
            "lastUpdated" : "10:29",
            "type" : "CHECKING",
            "number" : "3333",
            "posted" : "$10,000.00",
            "available" : "$9,000.00"
          } ],
          "totalPosted" : "$40,000.00",
          "totalAvailable" : "$36,000.00"
        }, {
          "type" : "CD_RETIREMENT",
          "isOpen" : true,
          "certificateDepositRetirementAccounts" : [ {
            "nick" : "Retirement 0",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "CD",
            "number" : "0000",
            "amount" : "$00.00"
          }, {
            "nick" : "Retirement 1",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "CD",
            "number" : "1111",
            "amount" : "$1,000.00"
          }, {
            "nick" : "Retirement 2",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "CD",
            "number" : "2222",
            "amount" : "$2,000.00"
          }, {
            "nick" : "Retirement 3",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "CD",
            "number" : "3333",
            "amount" : "$3,000.00"
          }, {
            "nick" : "Retirement 4",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "CD",
            "number" : "4444",
            "amount" : "$4,000.00"
          } ],
          "total" : "$10,000.00"
        }, {
          "type" : "INVESTMENT",
          "isOpen" : false,
          "investmentAccounts" : [ {
            "nick" : "Credit 0",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "INV",
            "number" : "0000",
            "amount" : "$00.00"
          }, {
            "nick" : "Credit 1",
            "bbvaCompassAccount" : true,
            "alert" : false,
            "lastUpdated" : "10:29",
            "type" : "INV",
            "number" : "1111",
            "amount" : "$1,000.00"
          }, {
            "nick" : "Credit 2",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "INV",
            "number" : "2222",
            "amount" : "$2,000.00"
          }, {
            "nick" : "Credit 3",
            "bbvaCompassAccount" : true,
            "alert" : false,
            "lastUpdated" : "10:29",
            "type" : "INV",
            "number" : "3333",
            "amount" : "$3,000.00"
          } ],
          "total" : "$6,000.00"
        }, {
          "type" : "CREDITCARD_LINEOFCREDIT_OVERDRAFTPROTECTION",
          "isOpen" : false,
          "creditCardLineCreditOverdraftProtectionAccounts" : [ {
            "nick" : "Credit 0",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "CREDIT_CARD",
            "number" : "0000",
            "posted" : "$00.00",
            "available" : 0,
            "nextDate" : "01/02/2014",
            "minAmount" : "$200.00"
          }, {
            "nick" : "Credit 1",
            "bbvaCompassAccount" : true,
            "alert" : false,
            "lastUpdated" : "10:29",
            "type" : "CREDIT_LINE",
            "number" : "1111",
            "posted" : "$200.00",
            "available" : 1000,
            "nextDate" : "01/02/2014",
            "minAmount" : "$200.00"
          }, {
            "nick" : "Credit 2",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "CREDIT_CARD",
            "number" : "2222",
            "posted" : "$400.00",
            "available" : 2000,
            "nextDate" : "01/02/2014",
            "minAmount" : "$200.00"
          }, {
            "nick" : "Credit 3",
            "bbvaCompassAccount" : true,
            "alert" : false,
            "lastUpdated" : "10:29",
            "type" : "CREDIT_LINE",
            "number" : "3333",
            "posted" : "$600.00",
            "available" : 3000,
            "nextDate" : "01/02/2014",
            "minAmount" : "$200.00"
          } ],
          "total" : "$1,200.00"
        }, {
          "type" : "LOAN_MORTGAGE",
          "isOpen" : false,
          "loanMortgateAccounts" : [ {
            "nick" : "Loan 0",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "LOAN_ALS",
            "number" : "0000",
            "payOff" : "$00.00",
            "nextDate" : "01/02/2014",
            "nextAmount" : "$00.00"
          }, {
            "nick" : "Loan 1",
            "bbvaCompassAccount" : true,
            "alert" : false,
            "lastUpdated" : "10:29",
            "type" : "LOAN_ALS",
            "number" : "1111",
            "payOff" : "$1,000.00",
            "nextDate" : "01/02/2014",
            "nextAmount" : "$200.00"
          }, {
            "nick" : "Loan 2",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "LOAN_LOC",
            "number" : "2222",
            "payOff" : "$2,000.00",
            "nextDate" : "01/02/2014",
            "nextAmount" : "$400.00"
          }, {
            "nick" : "Loan 3",
            "bbvaCompassAccount" : true,
            "alert" : false,
            "lastUpdated" : "10:29",
            "type" : "LOAN_LOC",
            "number" : "3333",
            "payOff" : "$3,000.00",
            "nextDate" : "01/02/2014",
            "nextAmount" : "$600.00"
          } ],
          "total" : "$6,000.00"
        }, {
          "type" : "REAL_ESTATE",
          "isOpen" : false,
          "realEstateAccounts" : [ {
            "nick" : "Real 0",
            "bbvaCompassAccount" : true,
            "percent" : "00.00%",
            "amount" : "$00.00"
          }, {
            "nick" : "Real 1",
            "bbvaCompassAccount" : true,
            "percent" : "10.00%",
            "amount" : "$10.00"
          }, {
            "nick" : "Real 2",
            "bbvaCompassAccount" : true,
            "percent" : "20.00%",
            "amount" : "$20.00"
          }, {
            "nick" : "Real 3",
            "bbvaCompassAccount" : true,
            "percent" : "30.00%",
            "amount" : "$30.00"
          }, {
            "nick" : "Real 4",
            "bbvaCompassAccount" : true,
            "percent" : "40.00%",
            "amount" : "$40.00"
          } ],
          "total" : "$100.00"
        }, {
          "type" : "REWARDS",
          "isOpen" : true,
          "rewardsAccounts" : [ {
            "nick" : "Rewards 0",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "REWARDS",
            "balance" : "$00.00",
            "number" : "0000"
          }, {
            "nick" : "Rewards 1",
            "bbvaCompassAccount" : true,
            "alert" : false,
            "lastUpdated" : "10:29",
            "type" : "REWARDS",
            "balance" : "$1,000.00",
            "number" : "1111"
          }, {
            "nick" : "Rewards 2",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "REWARDS",
            "balance" : "$2,000.00",
            "number" : "2222"
          }, {
            "nick" : "Rewards 3",
            "bbvaCompassAccount" : true,
            "alert" : false,
            "lastUpdated" : "10:29",
            "type" : "REWARDS",
            "balance" : "$3,000.00",
            "number" : "3333"
          } ]
        } ]}


## Account Summary PDF [/accountsummary/pdf]
### [GET]

+ Response 200

## Account Summary EXCEL [/accountsummary/xlsx]
### [GET]

+ Response 200


# Group Mocks COMPSBA-186
## Account Summary Load [/accountsummary/load?mock=COMPSBA-186]

###[GET]
<https://medianet.atlassian.net/browse/COMPSBA-186>

+ Response 200 (application/json)

        {"summary":
        {
          "menu" : {
            "summary" : {
              "url" : "/SBA/app/accountsummary/load",
              "active" : true
            }
          },
          "profile" : {
            "name" : "John McClane",
            "messages" : 5,
            "lastSignIn" : {
              "iso8601" : "2014-01-02T10:28:59.527Z",
              "humanReadability" : "Thu, 01/02/2014 at 10:28 AM"
            }
          },
          "widgets" : [ {
            "type" : "CHECKING_SAVING",
            "isOpen" : true,
            "checkingSavingMoneyMarketAccounts" : [ {
            } ],
            "totalPosted" : "$00.00",
            "totalAvailable" : "$00.00"
          }, {
            "type" : "CD_RETIREMENT",
            "isOpen" : true,
            "certificateDepositRetirementAccounts" : [ {
            } ],
            "total" : "$00.00"
          }, {
            "type" : "CREDITCARD_LINEOFCREDIT_OVERDRAFTPROTECTION",
            "isOpen" : true,
            "creditCardLineCreditOverdraftProtectionAccounts" : [ {
            } ],
            "total" : "$00.00"
          } ]
        }}
        
## Account Summary con filtro [/accountsummary/load/{filter}?mock=COMPSBA-186]

### [GET]
<https://medianet.atlassian.net/browse/COMPSBA-186>
+ Parameters
    + filter (required, enumeration) ... compass, external, personal, business

+ Response 200 (application/json)
    
        {"widgets":
        [ {
          "type" : "CHECKING_SAVING",
          "isOpen" : true,
          "checkingSavingMoneyMarketAccounts" : [ {
          } ],
          "totalPosted" : "$00.00",
          "totalAvailable" : "$00.00"
        }, {
          "type" : "CD_RETIREMENT",
          "isOpen" : true,
          "certificateDepositRetirementAccounts" : [ {
          } ],
          "total" : "$00.00"
        }, {
          "type" : "CREDITCARD_LINEOFCREDIT_OVERDRAFTPROTECTION",
          "isOpen" : true,
          "creditCardLineCreditOverdraftProtectionAccounts" : [ {
          } ],
          "total" : "$00.00"
        } ]}
        
# Group Mocks COMPSBA-188
## Account Summary Load [/accountsummary/load?mock=COMPSBA-188]

###[GET]
<https://medianet.atlassian.net/browse/COMPSBA-188>

+ Response 200 (application/json)

        {"summary":
        {
          "menu" : {
            "summary" : {
              "url" : "/SBA/app/accountsummary/load",
              "active" : true
            }
          },
          "profile" : {
            "name" : "John McClane",
            "messages" : 5,
            "lastSignIn" : {
              "iso8601" : "2014-01-02T10:28:59.746Z",
              "humanReadability" : "Thu, 01/02/2014 at 10:28 AM"
            }
          },
          "widgets" : [ {
            "type" : "CREDITCARD_LINEOFCREDIT_OVERDRAFTPROTECTION",
            "isOpen" : true,
            "creditCardLineCreditOverdraftProtectionAccounts" : [ {
              "nick" : "Credit 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:28",
              "type" : "CREDIT_CARD",
              "number" : "0000",
              "posted" : "$00.00",
              "available" : 0,
              "nextDate" : "01/02/2014",
              "minAmount" : "$200.00"
            }, {
              "nick" : "Credit 1",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:28",
              "type" : "CREDIT_LINE",
              "number" : "1111",
              "posted" : "$200.00",
              "available" : 1000,
              "nextDate" : "01/02/2014",
              "minAmount" : "$200.00"
            }, {
              "nick" : "Credit 2",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "10:28",
              "type" : "CREDIT_CARD",
              "number" : "2222",
              "posted" : "$400.00",
              "available" : 2000,
              "nextDate" : "01/02/2014",
              "minAmount" : "$200.00"
            }, {
              "nick" : "Credit 3",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "10:28",
              "type" : "CREDIT_LINE",
              "number" : "3333",
              "posted" : "$600.00",
              "available" : 3000,
              "nextDate" : "01/02/2014",
              "minAmount" : "$200.00"
            } ],
            "total" : "$1,200.00"
          } ]
        }}
        
## Account Summary con filtro [/accountsummary/load/{filter}?mock=COMPSBA-188]

### [GET]
<https://medianet.atlassian.net/browse/COMPSBA-188>
+ Parameters
    + filter (required, enumeration) ... compass, external, personal, business

+ Response 200 (application/json)
    
        {"widgets":
        [ {
          "type" : "CREDITCARD_LINEOFCREDIT_OVERDRAFTPROTECTION",
          "isOpen" : true,
          "creditCardLineCreditOverdraftProtectionAccounts" : [ {
            "nick" : "Credit 0",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "CREDIT_CARD",
            "number" : "0000",
            "posted" : "$00.00",
            "available" : 0,
            "nextDate" : "01/02/2014",
            "minAmount" : "$200.00"
          }, {
            "nick" : "Credit 1",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "CREDIT_LINE",
            "number" : "1111",
            "posted" : "$200.00",
            "available" : 1000,
            "nextDate" : "01/02/2014",
            "minAmount" : "$200.00"
          }, {
            "nick" : "Credit 2",
            "bbvaCompassAccount" : true,
            "alert" : false,
            "lastUpdated" : "10:29",
            "type" : "CREDIT_CARD",
            "number" : "2222",
            "posted" : "$400.00",
            "available" : 2000,
            "nextDate" : "01/02/2014",
            "minAmount" : "$200.00"
          }, {
            "nick" : "Credit 3",
            "bbvaCompassAccount" : true,
            "alert" : false,
            "lastUpdated" : "10:29",
            "type" : "CREDIT_LINE",
            "number" : "3333",
            "posted" : "$600.00",
            "available" : 3000,
            "nextDate" : "01/02/2014",
            "minAmount" : "$200.00"
          } ],
          "total" : "$1,200.00"
        } ]}
        
# Group Mocks COMPSBA-189
## Account Summary Load [/accountsummary/load?mock=COMPSBA-189]

###[GET]
<https://medianet.atlassian.net/browse/COMPSBA-189>

+ Response 200 (application/json)

        {"summary":
        {
          "menu" : {
            "summary" : {
              "url" : "/SBA/app/accountsummary/load",
              "active" : true
            }
          },
          "profile" : {
            "name" : "John McClane",
            "messages" : 5,
            "lastSignIn" : {
              "iso8601" : "2014-01-02T10:28:59.863Z",
              "humanReadability" : "Thu, 01/02/2014 at 10:28 AM"
            }
          },
          "widgets" : [ {
            "type" : "CREDITCARD_LINEOFCREDIT_OVERDRAFTPROTECTION",
            "isOpen" : true,
            "creditCardLineCreditOverdraftProtectionAccounts" : [ {
            } ],
            "total" : "$00.00"
          } ]
        }}
        
## Account Summary con filtro [/accountsummary/load/{filter}?mock=COMPSBA-189]

### [GET]
<https://medianet.atlassian.net/browse/COMPSBA-189>

+ Parameters
    + filter (required, enumeration) ... compass, external, personal, business

+ Response 200 (application/json)
    
        {"widgets":
        [ {
          "type" : "CREDITCARD_LINEOFCREDIT_OVERDRAFTPROTECTION",
          "isOpen" : true,
          "creditCardLineCreditOverdraftProtectionAccounts" : [ {
          } ],
          "total" : "$00.00"
        } ]}
        
# Group Mocks COMPSBA-192
## Account Summary Load [/accountsummary/load?mock=COMPSBA-192]

###[GET]
<https://medianet.atlassian.net/browse/COMPSBA-192>

+ Response 200 (application/json)

        {"summary":
        {
          "menu" : {
            "summary" : {
              "url" : "/SBA/app/accountsummary/load",
              "active" : true
            }
          },
          "profile" : {
            "name" : "John McClane",
            "messages" : 5,
            "lastSignIn" : {
              "iso8601" : "2014-01-02T10:28:59.949Z",
              "humanReadability" : "Thu, 01/02/2014 at 10:28 AM"
            }
          },
          "widgets" : [ {
            "type" : "CHECKING_SAVING",
            "isOpen" : true,
            "checkingSavingMoneyMarketAccounts" : [ {
              "nick" : "Checking 1",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:28",
              "type" : "CHECKING",
              "number" : "0000",
              "posted" : "$10,000.00",
              "available" : "$9,000.00"
            }, {
              "nick" : "Checking 2",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:28",
              "type" : "CHECKING",
              "number" : "1111",
              "posted" : "$10,000.00",
              "available" : "$9,000.00"
            }, {
              "nick" : "Checking 3",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "10:28",
              "type" : "CHECKING",
              "number" : "2222",
              "posted" : "$10,000.00",
              "available" : "$9,000.00"
            }, {
              "nick" : "Checking 4",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "10:28",
              "type" : "CHECKING",
              "number" : "3333",
              "posted" : "$10,000.00",
              "available" : "$9,000.00"
            } ],
            "totalPosted" : "$40,000.00",
            "totalAvailable" : "$36,000.00"
          } ]
        }}
        
## Account Summary con filtro [/accountsummary/load/{filter}?mock=COMPSBA-192]

### [GET]
<https://medianet.atlassian.net/browse/COMPSBA-192>

+ Response 200 (application/json)

        {"widgets":
        [ {
          "type" : "CHECKING_SAVING",
          "isOpen" : true,
          "checkingSavingMoneyMarketAccounts" : [ {
            "nick" : "Checking 1",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "CHECKING",
            "number" : "0000",
            "posted" : "$10,000.00",
            "available" : "$9,000.00"
          }, {
            "nick" : "Checking 2",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "CHECKING",
            "number" : "1111",
            "posted" : "$10,000.00",
            "available" : "$9,000.00"
          }, {
            "nick" : "Checking 3",
            "bbvaCompassAccount" : true,
            "alert" : false,
            "lastUpdated" : "10:29",
            "type" : "CHECKING",
            "number" : "2222",
            "posted" : "$10,000.00",
            "available" : "$9,000.00"
          }, {
            "nick" : "Checking 4",
            "bbvaCompassAccount" : true,
            "alert" : false,
            "lastUpdated" : "10:29",
            "type" : "CHECKING",
            "number" : "3333",
            "posted" : "$10,000.00",
            "available" : "$9,000.00"
          } ],
          "totalPosted" : "$40,000.00",
          "totalAvailable" : "$36,000.00"
        } ]}
        
# Group Mocks COMPSBA-193
## Account Summary Load [/accountsummary/load?mock=COMPSBA-193]

###[GET]
<https://medianet.atlassian.net/browse/COMPSBA-193>

+ Response 200 (application/json)

        {"summary":
        {
          "menu" : {
            "summary" : {
              "url" : "/SBA/app/accountsummary/load",
              "active" : true
            }
          },
          "profile" : {
            "name" : "John McClane",
            "messages" : 5,
            "lastSignIn" : {
              "iso8601" : "2014-01-02T10:29:00.038Z",
              "humanReadability" : "Thu, 01/02/2014 at 10:29 AM"
            }
          },
          "widgets" : [ {
            "type" : "CHECKING_SAVING",
            "isOpen" : true,
            "checkingSavingMoneyMarketAccounts" : [ {
            } ],
            "totalPosted" : "$00.00",
            "totalAvailable" : "$00.00"
          } ]
        }}
        
## Account Summary con filtro [/accountsummary/load/{filter}?mock=COMPSBA-193]

### [GET]
<https://medianet.atlassian.net/browse/COMPSBA-193>

+ Response 200 (application/json)

        {"widgets":
        [ {
          "type" : "CHECKING_SAVING",
          "isOpen" : true,
          "checkingSavingMoneyMarketAccounts" : [ {
          } ],
          "totalPosted" : "$00.00",
          "totalAvailable" : "$00.00"
        } ]}

# Group Mocks COMPSBA-197
## Account Summary Load [/accountsummary/load?mock=COMPSBA-197]

###[GET]
<https://medianet.atlassian.net/browse/COMPSBA-197>

+ Response 200 (application/json)

        {"summary":
        {
          "menu" : {
            "summary" : {
              "url" : "/SBA/app/accountsummary/load",
              "active" : true
            }
          },
          "profile" : {
            "name" : "John McClane",
            "messages" : 5,
            "lastSignIn" : {
              "iso8601" : "2014-01-02T10:29:00.145Z",
              "humanReadability" : "Thu, 01/02/2014 at 10:29 AM"
            }
          },
          "widgets" : [ {
            "type" : "CD_RETIREMENT",
            "isOpen" : true,
            "certificateDepositRetirementAccounts" : [ {
              "nick" : "Retirement 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:29",
              "type" : "CD",
              "number" : "0000",
              "amount" : "$00.00"
            }, {
              "nick" : "Retirement 1",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:29",
              "type" : "CD",
              "number" : "1111",
              "amount" : "$1,000.00"
            }, {
              "nick" : "Retirement 2",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:29",
              "type" : "CD",
              "number" : "2222",
              "amount" : "$2,000.00"
            }, {
              "nick" : "Retirement 3",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "10:29",
              "type" : "CD",
              "number" : "3333",
              "amount" : "$3,000.00"
            } ],
            "total" : "$6,000.00"
          } ]
        }}
        
## Account Summary con filtro [/accountsummary/load/{filter}?mock=COMPSBA-197]

### [GET]
<https://medianet.atlassian.net/browse/COMPSBA-197>

+ Response 200 (application/json)

        {"widgets":
        [ {
          "type" : "CD_RETIREMENT",
          "isOpen" : true,
          "certificateDepositRetirementAccounts" : [ {
            "nick" : "Retirement 0",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "CD",
            "number" : "0000",
            "amount" : "$00.00"
          }, {
            "nick" : "Retirement 1",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "CD",
            "number" : "1111",
            "amount" : "$1,000.00"
          }, {
            "nick" : "Retirement 2",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "CD",
            "number" : "2222",
            "amount" : "$2,000.00"
          }, {
            "nick" : "Retirement 3",
            "bbvaCompassAccount" : true,
            "alert" : true,
            "lastUpdated" : "10:29",
            "type" : "CD",
            "number" : "3333",
            "amount" : "$3,000.00"
          } ],
          "total" : "$6,000.00"
        } ]}

# Group Mocks COMPSBA-198
## Account Summary Load [/accountsummary/load?mock=COMPSBA-198]

###[GET]
<https://medianet.atlassian.net/browse/COMPSBA-198>

+ Response 200 (application/json)

        {"summary":
        {
          "menu" : {
            "summary" : {
              "url" : "/SBA/app/accountsummary/load",
              "active" : true
            }
          },
          "profile" : {
            "name" : "John McClane",
            "messages" : 5,
            "lastSignIn" : {
              "iso8601" : "2014-01-02T10:29:00.296Z",
              "humanReadability" : "Thu, 01/02/2014 at 10:29 AM"
            }
          },
          "widgets" : [ {
            "type" : "CD_RETIREMENT",
            "isOpen" : true,
            "certificateDepositRetirementAccounts" : [ {
            } ],
            "total" : "$00.00"
          } ]
        }}
        
## Account Summary con filtro [/accountsummary/load/{filter}?mock=COMPSBA-198]

### [GET]
<https://medianet.atlassian.net/browse/COMPSBA-198>

+ Response 200 (application/json)

        {"widgets":
        [ {
          "type" : "CD_RETIREMENT",
          "isOpen" : true,
          "certificateDepositRetirementAccounts" : [ {
          } ],
          "total" : "$00.00"
        } ]}

# Group Mocks COMPSBA-203
## Account Summary Load [/accountsummary/load?mock=COMPSBA-203]

###[GET]
<https://medianet.atlassian.net/browse/COMPSBA-203>

+ Response 200 (application/json)

        {"summary":
        {
          "menu" : {
            "summary" : {
              "url" : "/SBA/app/accountsummary/load",
              "active" : true
            }
          },
          "profile" : {
            "name" : "Hans Gruber",
            "messages" : 5,
            "lastSignIn" : {
              "iso8601" : "2014-01-02T10:29:00.386Z",
              "humanReadability" : "Thu, 01/02/2014 at 10:29 AM"
            }
          },
          "widgets" : [ {
            "type" : "CHECKING_SAVING",
            "isOpen" : true,
            "checkingSavingMoneyMarketAccounts" : [ {
            } ],
            "totalPosted" : "$00.00",
            "totalAvailable" : "$00.00"
          }, {
            "type" : "CD_RETIREMENT",
            "isOpen" : true,
            "certificateDepositRetirementAccounts" : [ {
            } ],
            "total" : "$00.00"
          }, {
            "type" : "INVESTMENT",
            "isOpen" : true,
            "investmentAccounts" : [ {
            } ],
            "total" : "$00.00"
          }, {
            "type" : "CREDITCARD_LINEOFCREDIT_OVERDRAFTPROTECTION",
            "isOpen" : true,
            "creditCardLineCreditOverdraftProtectionAccounts" : [ {
            } ],
            "total" : "$00.00"
          }, {
            "type" : "LOAN_MORTGAGE",
            "isOpen" : true,
            "loanMortgateAccounts" : [ {
            } ],
            "total" : "$00.00"
          }, {
            "type" : "REAL_ESTATE",
            "isOpen" : true,
            "realEstateAccounts" : [ {
            } ],
            "total" : "$00.00"
          }, {
            "type" : "REWARDS",
            "isOpen" : true,
            "rewardsAccounts" : [ {
            } ]
          } ]
        }}
        
# Group Mocks COMPSBA-208
## Account Summary Load [/accountsummary/load?mock=COMPSBA-208]

###[GET]
<https://medianet.atlassian.net/browse/COMPSBA-208>

+ Response 200 (application/json)

        {"summary":
        {
          "menu" : {
            "summary" : {
              "url" : "/SBA/app/accountsummary/load",
              "active" : true
            }
          },
          "profile" : {
            "name" : "John McClane",
            "messages" : 42,
            "lastSignIn" : {
              "iso8601" : "2014-01-02T10:29:00.647Z",
              "humanReadability" : "Thu, 01/02/2014 at 10:29 AM"
            }
          },
          "widgets" : [ {
            "type" : "CHECKING_SAVING",
            "isOpen" : true,
            "checkingSavingMoneyMarketAccounts" : [ {
            } ],
            "totalPosted" : "$00.00",
            "totalAvailable" : "$00.00"
          }, {
            "type" : "CD_RETIREMENT",
            "isOpen" : true,
            "certificateDepositRetirementAccounts" : [ {
            } ],
            "total" : "$00.00"
          }, {
            "type" : "INVESTMENT",
            "isOpen" : true,
            "investmentAccounts" : [ {
            } ],
            "total" : "$00.00"
          }, {
            "type" : "CREDITCARD_LINEOFCREDIT_OVERDRAFTPROTECTION",
            "isOpen" : true,
            "creditCardLineCreditOverdraftProtectionAccounts" : [ {
            } ],
            "total" : "$00.00"
          }, {
            "type" : "LOAN_MORTGAGE",
            "isOpen" : true,
            "loanMortgateAccounts" : [ {
            } ],
            "total" : "$00.00"
          }, {
            "type" : "REAL_ESTATE",
            "isOpen" : true,
            "realEstateAccounts" : [ {
            } ],
            "total" : "$00.00"
          }, {
            "type" : "REWARDS",
            "isOpen" : true,
            "rewardsAccounts" : [ {
            } ]
          } ]
        }}

# Group Mocks COMPSBA-212
## Account Summary Load [/accountsummary/load?mock=COMPSBA-212]

###[GET]
<https://medianet.atlassian.net/browse/COMPSBA-212>

+ Response 200 (application/json)

        {"summary":
        {
          "menu" : {
            "summary" : {
              "url" : "/SBA/app/accountsummary/load",
              "active" : true
            }
          },
          "profile" : {
            "name" : "John McClane",
            "messages" : 5,
            "lastSignIn" : {
              "iso8601" : "2000-06-22T14:55:42.000Z",
              "humanReadability" : "Thu, 06/22/2000 at 02:55 PM"
            }
          },
          "widgets" : [ {
            "type" : "CHECKING_SAVING",
            "isOpen" : true,
            "checkingSavingMoneyMarketAccounts" : [ {
            } ],
            "totalPosted" : "$00.00",
            "totalAvailable" : "$00.00"
          }, {
            "type" : "CD_RETIREMENT",
            "isOpen" : true,
            "certificateDepositRetirementAccounts" : [ {
            } ],
            "total" : "$00.00"
          }, {
            "type" : "INVESTMENT",
            "isOpen" : true,
            "investmentAccounts" : [ {
            } ],
            "total" : "$00.00"
          }, {
            "type" : "CREDITCARD_LINEOFCREDIT_OVERDRAFTPROTECTION",
            "isOpen" : true,
            "creditCardLineCreditOverdraftProtectionAccounts" : [ {
            } ],
            "total" : "$00.00"
          }, {
            "type" : "LOAN_MORTGAGE",
            "isOpen" : true,
            "loanMortgateAccounts" : [ {
            } ],
            "total" : "$00.00"
          }, {
            "type" : "REAL_ESTATE",
            "isOpen" : true,
            "realEstateAccounts" : [ {
            } ],
            "total" : "$00.00"
          }, {
            "type" : "REWARDS",
            "isOpen" : true,
            "rewardsAccounts" : [ {
            } ]
          } ]
        }}
