FORMAT: 1A
HOST: http://docs.sba.apiary.io/

# SBA-Front API
SBA-Front API 

# Group Account Summary
Services involved in **Account Summary API**

## Account Summary [/hbs/accountsummary/load]
### base load [GET]
+ Response 200 (application/json)

        {
          "widgets" : [ {
            "type" : "CHECKING_SAVING",
            "isOpen" : true,
            "totalPosted" : "$40000.0",
            "totalAvailable" : "$36000.0",
            "checkingSavingMoneyMarketAccounts" : [ {
              "nick" : "Checking 1",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CHECKING",
              "number" : "0000",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 2",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "CHECKING",
              "number" : "1111",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 3",
              "bbvaCompassAccount" : false,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CHECKING",
              "number" : "2222",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 4",
              "bbvaCompassAccount" : false,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "CHECKING",
              "number" : "3333",
              "posted" : 10000,
              "available" : 9000
            } ]
          }, {
            "type" : "CD_RETIREMENT",
            "total" : "$10000.0",
            "isOpen" : true,
            "certificateDepositRetirementAccounts" : [ {
              "nick" : "Retirement 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "0000",
              "amount" : 0
            }, {
              "nick" : "Retirement 1",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "1111",
              "amount" : 1000
            }, {
              "nick" : "Retirement 2",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "2222",
              "amount" : 2000
            }, {
              "nick" : "Retirement 3",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "3333",
              "amount" : 3000
            }, {
              "nick" : "Retirement 4",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "4444",
              "amount" : 4000
            } ]
          }, {
            "type" : "CREDITCARD_LINEOFCREDIT_OVERDRAFTPROTECTION",
            "total" : "$1200.0",
            "isOpen" : true,
            "creditCardLineCreditOverdraftProtectionAccounts" : [ {
              "nick" : "Credit 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CREDIT_CARD",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 0
              }, {
                "key" : "Available credit",
                "value" : 0
              } ],
              "number" : "0000"
            }, {
              "nick" : "Credit 1",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "CREDIT_LINE",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 200
              }, {
                "key" : "Available credit",
                "value" : 1000
              } ],
              "number" : "1111"
            }, {
              "nick" : "Credit 2",
              "bbvaCompassAccount" : false,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CREDIT_CARD",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 400
              }, {
                "key" : "Available credit",
                "value" : 2000
              } ],
              "number" : "2222"
            }, {
              "nick" : "Credit 3",
              "bbvaCompassAccount" : false,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "CREDIT_LINE",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 600
              }, {
                "key" : "Available credit",
                "value" : 3000
              } ],
              "number" : "3333"
            } ]
          }, {
            "type" : "LOAN_MORTGAGE",
            "total" : "$6000.0",
            "isOpen" : true,
            "loanMortgateAccounts" : [ {
              "nick" : "Loan 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "LOAN_ALS",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 0
              }, {
                "key" : "Next Payment Date",
                "value" : "11/19/2013"
              }, {
                "key" : "Min. Payment Amount",
                "value" : 0
              } ],
              "number" : "0000"
            }, {
              "nick" : "Loan 1",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "LOAN_ALS",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 1000
              }, {
                "key" : "Next Payment Date",
                "value" : "11/19/2013"
              }, {
                "key" : "Min. Payment Amount",
                "value" : 200
              } ],
              "number" : "1111"
            }, {
              "nick" : "Loan 2",
              "bbvaCompassAccount" : false,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "LOAN_LOC",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 2000
              }, {
                "key" : "Next Payment Date",
                "value" : "11/19/2013"
              }, {
                "key" : "Min. Payment Amount",
                "value" : 400
              } ],
              "number" : "2222"
            }, {
              "nick" : "Loan 3",
              "bbvaCompassAccount" : false,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "LOAN_LOC",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 3000
              }, {
                "key" : "Next Payment Date",
                "value" : "11/19/2013"
              }, {
                "key" : "Min. Payment Amount",
                "value" : 600
              } ],
              "number" : "3333"
            } ]
          }, {
            "type" : "INVESTMENT",
            "total" : "$6000.0",
            "isOpen" : true,
            "investmentAccounts" : [ {
              "nick" : "Credit 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "INV",
              "number" : "0000",
              "amount" : 0
            }, {
              "nick" : "Credit 1",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "INV",
              "number" : "1111",
              "amount" : 1000
            }, {
              "nick" : "Credit 2",
              "bbvaCompassAccount" : false,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "INV",
              "number" : "2222",
              "amount" : 2000
            }, {
              "nick" : "Credit 3",
              "bbvaCompassAccount" : false,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "INV",
              "number" : "3333",
              "amount" : 3000
            } ]
          }, {
            "type" : "REAL_ESTATE",
            "total" : "$15000.0",
            "isOpen" : true,
            "realEstateAccounts" : [ {
              "nick" : "Real 0",
              "homeEquityPercent" : "0.00%",
              "percent" : "0.00%%",
              "amount" : 0
            }, {
              "nick" : "Real 1",
              "homeEquityPercent" : "10.00%",
              "percent" : "10.00%%",
              "amount" : 1500
            }, {
              "nick" : "Real 2",
              "homeEquityPercent" : "20.00%",
              "percent" : "20.00%%",
              "amount" : 3000
            }, {
              "nick" : "Real 3",
              "homeEquityPercent" : "30.00%",
              "percent" : "30.00%%",
              "amount" : 4500
            }, {
              "nick" : "Real 4",
              "homeEquityPercent" : "40.00%",
              "percent" : "40.00%%",
              "amount" : 6000
            } ]
          }, {
            "type" : "REWARDS",
            "isOpen" : true,
            "rewardsAccounts" : [ {
              "nick" : "Rewards 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "REWARDS",
              "balance" : 0,
              "number" : "0000"
            }, {
              "nick" : "Rewards 1",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "REWARDS",
              "balance" : 1000,
              "number" : "1111"
            }, {
              "nick" : "Rewards 2",
              "bbvaCompassAccount" : false,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "REWARDS",
              "balance" : 2000,
              "number" : "2222"
            }, {
              "nick" : "Rewards 3",
              "bbvaCompassAccount" : false,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "REWARDS",
              "balance" : 3000,
              "number" : "3333"
            } ]
          } ]
        }
        
## Yoodle [/hbs/accountsummary/yodlee]
### yoodle [GET]
+ Response 200 (application/json)
      
        {
          "widgets" : [ {
            "type" : "CHECKING_SAVING",
            "isOpen" : true,
            "totalPosted" : "$40000.0",
            "totalAvailable" : "$36000.0",
            "checkingSavingMoneyMarketAccounts" : [ {
              "nick" : "Checking 1",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CHECKING",
              "number" : "0000",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 2",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "CHECKING",
              "number" : "1111",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 3",
              "bbvaCompassAccount" : false,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CHECKING",
              "number" : "2222",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 4",
              "bbvaCompassAccount" : false,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "CHECKING",
              "number" : "3333",
              "posted" : 10000,
              "available" : 9000
            } ]
          }, {
            "type" : "CD_RETIREMENT",
            "total" : "$55000.0",
            "isOpen" : true,
            "certificateDepositRetirementAccounts" : [ {
              "nick" : "Retirement 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "0000",
              "amount" : 0
            }, {
              "nick" : "Retirement 1",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "1111",
              "amount" : 1000
            }, {
              "nick" : "Retirement 2",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "2222",
              "amount" : 2000
            }, {
              "nick" : "Retirement 3",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "3333",
              "amount" : 3000
            }, {
              "nick" : "Retirement 4",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "4444",
              "amount" : 4000
            }, {
              "nick" : "Retirement 5",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "5555",
              "amount" : 5000
            }, {
              "nick" : "Retirement 6",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "6666",
              "amount" : 6000
            }, {
              "nick" : "Retirement 7",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "7777",
              "amount" : 7000
            }, {
              "nick" : "Retirement 8",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "8888",
              "amount" : 8000
            }, {
              "nick" : "Retirement 9",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "9999",
              "amount" : 9000
            }, {
              "nick" : "Retirement 10",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "10101010",
              "amount" : 10000
            } ]
          }, {
            "type" : "CREDITCARD_LINEOFCREDIT_OVERDRAFTPROTECTION",
            "total" : "$1200.0",
            "isOpen" : true,
            "creditCardLineCreditOverdraftProtectionAccounts" : [ {
              "nick" : "Credit 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CREDIT_CARD",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 0
              }, {
                "key" : "Available credit",
                "value" : 0
              } ],
              "number" : "0000"
            }, {
              "nick" : "Credit 1",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "CREDIT_LINE",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 200
              }, {
                "key" : "Available credit",
                "value" : 1000
              } ],
              "number" : "1111"
            }, {
              "nick" : "Credit 2",
              "bbvaCompassAccount" : false,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CREDIT_CARD",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 400
              }, {
                "key" : "Available credit",
                "value" : 2000
              } ],
              "number" : "2222"
            }, {
              "nick" : "Credit 3",
              "bbvaCompassAccount" : false,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "CREDIT_LINE",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 600
              }, {
                "key" : "Available credit",
                "value" : 3000
              } ],
              "number" : "3333"
            } ]
          }, {
            "type" : "LOAN_MORTGAGE",
            "total" : "$6000.0",
            "isOpen" : true,
            "loanMortgateAccounts" : [ {
              "nick" : "Loan 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "LOAN_ALS",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 0
              }, {
                "key" : "Next Payment Date",
                "value" : "11/19/2013"
              }, {
                "key" : "Min. Payment Amount",
                "value" : 0
              } ],
              "number" : "0000"
            }, {
              "nick" : "Loan 1",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "LOAN_ALS",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 1000
              }, {
                "key" : "Next Payment Date",
                "value" : "11/19/2013"
              }, {
                "key" : "Min. Payment Amount",
                "value" : 200
              } ],
              "number" : "1111"
            }, {
              "nick" : "Loan 2",
              "bbvaCompassAccount" : false,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "LOAN_LOC",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 2000
              }, {
                "key" : "Next Payment Date",
                "value" : "11/19/2013"
              }, {
                "key" : "Min. Payment Amount",
                "value" : 400
              } ],
              "number" : "2222"
            }, {
              "nick" : "Loan 3",
              "bbvaCompassAccount" : false,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "LOAN_LOC",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 3000
              }, {
                "key" : "Next Payment Date",
                "value" : "11/19/2013"
              }, {
                "key" : "Min. Payment Amount",
                "value" : 600
              } ],
              "number" : "3333"
            } ]
          }, {
            "type" : "INVESTMENT",
            "total" : "$6000.0",
            "isOpen" : true,
            "investmentAccounts" : [ {
              "nick" : "Credit 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "INV",
              "number" : "0000",
              "amount" : 0
            }, {
              "nick" : "Credit 1",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "INV",
              "number" : "1111",
              "amount" : 1000
            }, {
              "nick" : "Credit 2",
              "bbvaCompassAccount" : false,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "INV",
              "number" : "2222",
              "amount" : 2000
            }, {
              "nick" : "Credit 3",
              "bbvaCompassAccount" : false,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "INV",
              "number" : "3333",
              "amount" : 3000
            } ]
          }, {
            "type" : "REAL_ESTATE",
            "total" : "$22500.0",
            "isOpen" : true,
            "realEstateAccounts" : [ {
              "nick" : "Real 0",
              "homeEquityPercent" : "0.00%",
              "percent" : "0.00%%",
              "amount" : 0
            }, {
              "nick" : "Real 1",
              "homeEquityPercent" : "10.00%",
              "percent" : "10.00%%",
              "amount" : 1500
            }, {
              "nick" : "Real 2",
              "homeEquityPercent" : "20.00%",
              "percent" : "20.00%%",
              "amount" : 3000
            }, {
              "nick" : "Real 3",
              "homeEquityPercent" : "30.00%",
              "percent" : "30.00%%",
              "amount" : 4500
            }, {
              "nick" : "Real 4",
              "homeEquityPercent" : "40.00%",
              "percent" : "40.00%%",
              "amount" : 6000
            }, {
              "nick" : "Real 5",
              "homeEquityPercent" : "50.00%",
              "percent" : "50.00%%",
              "amount" : 7500
            } ]
          }, {
            "type" : "REWARDS",
            "isOpen" : true,
            "rewardsAccounts" : [ {
              "nick" : "Rewards 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "REWARDS",
              "balance" : 0,
              "number" : "0000"
            }, {
              "nick" : "Rewards 1",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "REWARDS",
              "balance" : 1000,
              "number" : "1111"
            }, {
              "nick" : "Rewards 2",
              "bbvaCompassAccount" : false,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "REWARDS",
              "balance" : 2000,
              "number" : "2222"
            }, {
              "nick" : "Rewards 3",
              "bbvaCompassAccount" : false,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "REWARDS",
              "balance" : 3000,
              "number" : "3333"
            }, {
              "nick" : "Rewards 4",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "REWARDS",
              "balance" : 4000,
              "number" : "4444"
            }, {
              "nick" : "Rewards 5",
              "bbvaCompassAccount" : false,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "REWARDS",
              "balance" : 5000,
              "number" : "5555"
            }, {
              "nick" : "Rewards 6",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "REWARDS",
              "balance" : 6000,
              "number" : "6666"
            }, {
              "nick" : "Rewards 7",
              "bbvaCompassAccount" : false,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "REWARDS",
              "balance" : 7000,
              "number" : "7777"
            }, {
              "nick" : "Rewards 8",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "REWARDS",
              "balance" : 8000,
              "number" : "8888"
            }, {
              "nick" : "Rewards 9",
              "bbvaCompassAccount" : false,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "REWARDS",
              "balance" : 9000,
              "number" : "9999"
            } ]
          } ]
        }
       

## Credit Card [/hbs/accountsummary/credit-card]
### credit card [GET]
El content-type json, se utilizará únicamente en modo de desarrollo, ya que para utilizar las llamadas AJAX será necesario solicitar el contenido como text/html

+ Request 

    + Headers

            Accept: text/html, application/json

+ Response 200 (application/json)

        {
          "widgets" : [ {
            "type" : "CHECKING_SAVING",
            "isOpen" : true,
            "totalPosted" : "$40000.0",
            "totalAvailable" : "$36000.0",
            "checkingSavingMoneyMarketAccounts" : [ {
              "nick" : "Checking 1",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CHECKING",
              "number" : "0000",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 2",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "CHECKING",
              "number" : "1111",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 3",
              "bbvaCompassAccount" : false,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CHECKING",
              "number" : "2222",
              "posted" : 10000,
              "available" : 9000
            }, {
              "nick" : "Checking 4",
              "bbvaCompassAccount" : false,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "CHECKING",
              "number" : "3333",
              "posted" : 10000,
              "available" : 9000
            } ]
          }, {
            "type" : "CD_RETIREMENT",
            "total" : "$10000.0",
            "isOpen" : true,
            "certificateDepositRetirementAccounts" : [ {
              "nick" : "Retirement 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "0000",
              "amount" : 0
            }, {
              "nick" : "Retirement 1",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "1111",
              "amount" : 1000
            }, {
              "nick" : "Retirement 2",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "2222",
              "amount" : 2000
            }, {
              "nick" : "Retirement 3",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "3333",
              "amount" : 3000
            }, {
              "nick" : "Retirement 4",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CD",
              "number" : "4444",
              "amount" : 4000
            } ]
          }, {
            "type" : "CREDITCARD_LINEOFCREDIT_OVERDRAFTPROTECTION",
            "total" : "$3000.0",
            "isOpen" : true,
            "creditCardLineCreditOverdraftProtectionAccounts" : [ {
              "nick" : "Credit 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CREDIT_CARD",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 0
              }, {
                "key" : "Available credit",
                "value" : 0
              } ],
              "number" : "0000"
            }, {
              "nick" : "Credit 1",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "CREDIT_LINE",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 200
              }, {
                "key" : "Available credit",
                "value" : 1000
              } ],
              "number" : "1111"
            }, {
              "nick" : "Credit 2",
              "bbvaCompassAccount" : false,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CREDIT_CARD",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 400
              }, {
                "key" : "Available credit",
                "value" : 2000
              } ],
              "number" : "2222"
            }, {
              "nick" : "Credit 3",
              "bbvaCompassAccount" : false,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "CREDIT_LINE",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 600
              }, {
                "key" : "Available credit",
                "value" : 3000
              } ],
              "number" : "3333"
            }, {
              "nick" : "Credit 4",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "CREDIT_LINE",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 800
              }, {
                "key" : "Available credit",
                "value" : 4000
              } ],
              "number" : "4444"
            }, {
              "nick" : "Credit 5",
              "bbvaCompassAccount" : false,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "CREDIT_LINE",
              "details" : [ {
                "key" : "Current Balance",
                "value" : 1000
              }, {
                "key" : "Available credit",
                "value" : 5000
              } ],
              "number" : "5555"
            } ]
          }, {
            "type" : "LOAN_MORTGAGE",
            "total" : "$6000.0",
            "isOpen" : true,
            "loanMortgateAccounts" : [ {
              "nick" : "Loan 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "LOAN_ALS",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 0
              }, {
                "key" : "Next Payment Date",
                "value" : "11/19/2013"
              }, {
                "key" : "Min. Payment Amount",
                "value" : 0
              } ],
              "number" : "0000"
            }, {
              "nick" : "Loan 1",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "LOAN_ALS",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 1000
              }, {
                "key" : "Next Payment Date",
                "value" : "11/19/2013"
              }, {
                "key" : "Min. Payment Amount",
                "value" : 200
              } ],
              "number" : "1111"
            }, {
              "nick" : "Loan 2",
              "bbvaCompassAccount" : false,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "LOAN_LOC",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 2000
              }, {
                "key" : "Next Payment Date",
                "value" : "11/19/2013"
              }, {
                "key" : "Min. Payment Amount",
                "value" : 400
              } ],
              "number" : "2222"
            }, {
              "nick" : "Loan 3",
              "bbvaCompassAccount" : false,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "LOAN_LOC",
              "details" : [ {
                "key" : "Payoff Balance",
                "value" : 3000
              }, {
                "key" : "Next Payment Date",
                "value" : "11/19/2013"
              }, {
                "key" : "Min. Payment Amount",
                "value" : 600
              } ],
              "number" : "3333"
            } ]
          }, {
            "type" : "INVESTMENT",
            "total" : "$6000.0",
            "isOpen" : true,
            "investmentAccounts" : [ {
              "nick" : "Credit 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "INV",
              "number" : "0000",
              "amount" : 0
            }, {
              "nick" : "Credit 1",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "INV",
              "number" : "1111",
              "amount" : 1000
            }, {
              "nick" : "Credit 2",
              "bbvaCompassAccount" : false,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "INV",
              "number" : "2222",
              "amount" : 2000
            }, {
              "nick" : "Credit 3",
              "bbvaCompassAccount" : false,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "INV",
              "number" : "3333",
              "amount" : 3000
            } ]
          }, {
            "type" : "REAL_ESTATE",
            "total" : "$15000.0",
            "isOpen" : true,
            "realEstateAccounts" : [ {
              "nick" : "Real 0",
              "homeEquityPercent" : "0.00%",
              "percent" : "0.00%%",
              "amount" : 0
            }, {
              "nick" : "Real 1",
              "homeEquityPercent" : "10.00%",
              "percent" : "10.00%%",
              "amount" : 1500
            }, {
              "nick" : "Real 2",
              "homeEquityPercent" : "20.00%",
              "percent" : "20.00%%",
              "amount" : 3000
            }, {
              "nick" : "Real 3",
              "homeEquityPercent" : "30.00%",
              "percent" : "30.00%%",
              "amount" : 4500
            }, {
              "nick" : "Real 4",
              "homeEquityPercent" : "40.00%",
              "percent" : "40.00%%",
              "amount" : 6000
            } ]
          }, {
            "type" : "REWARDS",
            "isOpen" : true,
            "rewardsAccounts" : [ {
              "nick" : "Rewards 0",
              "bbvaCompassAccount" : true,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "REWARDS",
              "balance" : 0,
              "number" : "0000"
            }, {
              "nick" : "Rewards 1",
              "bbvaCompassAccount" : true,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "REWARDS",
              "balance" : 1000,
              "number" : "1111"
            }, {
              "nick" : "Rewards 2",
              "bbvaCompassAccount" : false,
              "alert" : true,
              "lastUpdated" : "01:45",
              "type" : "REWARDS",
              "balance" : 2000,
              "number" : "2222"
            }, {
              "nick" : "Rewards 3",
              "bbvaCompassAccount" : false,
              "alert" : false,
              "lastUpdated" : "01:45",
              "type" : "REWARDS",
              "balance" : 3000,
              "number" : "3333"
            } ]
          } ]
        }
        

+ Response 200 (text/html)

        <html>
             <body>
                 to be defined
             </body>
        </html>